/**
 * Options for the server
 */
export interface ServerOptions {

  /**
   * Environment
   * e.g. 'development'
   */
  env: string;

  /**
   * Configuration of the GraphQL module
   */
  graphQl: {

    /**
     * GraphQL module configuration
     * see https://docs.nestjs.com/graphql/quick-start
     */
    [key: string]: any,

    /**
     * Autogenerated schema file
     * e.g. 'schema.gql'
     */
    autoSchemaFile: string,

    /**
     * Determines whether or not to install subscription handlers
     * e.g. true
     */
    installSubscriptionHandlers: boolean,
  }

  /**
   * Port number of the server
   * e.g. 8080
   */
  port: number;

  /**
   * Configuration of TypeORM
   * e.g. for MongoDB: https://github.com/typeorm/typeorm/blob/master/docs/connection-options.md#mongodb-connection-options
   */
  typeOrm: {

    /**
     * TypeORM configuration
     * see https://github.com/typeorm/typeorm/blob/master/docs/connection-options.md
     */
    [key: string]: any,

    /**
     * Type of database
     * e.g. 'mongodb'
     */
    type: any,

    /**
     * Host of the database
     * e.g. 'localhost'
     */
    host: string,

    /**
     * Port of the database
     * e.g. 27017
     */
    port: number,

    /**
     * Name of the database
     * e.g. 'my-project'
     */
    database: string,

    /**
     * Indicates if database schema should be auto created on every application launch
     * e.g. false
     */
    synchronize: boolean,

    /**
     * Entities to be loaded and used for this connection
     * e.g. [Post, Category, 'entity/*.js', 'modules/** /entity/*.js']
     */
    entities: string[],

    /**
     * Determines whether or not to use the new url parser
     * e.g. true
     */
    useNewUrlParser: boolean
  };

  /**
   * Determines whether or not to integrate models from the module
   * additionally into TypeORM
   */
  typeOrmModelIntegration: boolean;
}
