import { passkey } from '@better-auth/passkey';
import { Logger } from '@nestjs/common';
import { betterAuth, BetterAuthPlugin } from 'better-auth';
import { mongodbAdapter } from 'better-auth/adapters/mongodb';
import { jwt, twoFactor } from 'better-auth/plugins';
import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';

import { resolveServerUrls, strippedApiHostname } from '../../common/helpers/cookies.helper';
import { IBetterAuth, ICorsConfig } from '../../common/interfaces/server-options.interface';
import { detectCookiePrefixDrift, resolveBetterAuthCookiePrefix } from './better-auth-cookie-prefix.helper';

/**
 * Type for better-auth instance with plugins
 */
export type BetterAuthInstance = ReturnType<typeof betterAuth>;

/**
 * Shared logger for all functions in this config module
 */
const logger = new Logger('BetterAuthConfig');

// ---------------------------------------------------------------------------
// Performance-optimized password hashing using Node.js native crypto.scrypt
//
// Better-Auth's default uses @noble/hashes scrypt which runs on the main
// event loop. Under concurrent load this blocks all requests while hashing.
// Node.js crypto.scrypt() offloads the work to the libuv thread pool,
// allowing the event loop to remain responsive.
//
// Parameters match Better-Auth's defaults exactly:
//   N=16384, r=16, p=1, dkLen=64, 16-byte salt
// ---------------------------------------------------------------------------

const SCRYPT_PARAMS = { maxmem: 128 * 16384 * 16 * 2, N: 16384, p: 1, r: 16 };
const SCRYPT_KEY_LENGTH = 64;

/**
 * Generates a cryptographically secure random secret.
 * Used as fallback when no BETTER_AUTH_SECRET is configured.
 *
 * NOTE: This secret is generated at server startup, meaning:
 * - All existing sessions become invalid on server restart
 * - This is acceptable for development environments
 * - For production, ALWAYS set BETTER_AUTH_SECRET to maintain sessions across restarts
 */
function generateSecureSecret(): string {
  return crypto.randomBytes(32).toString('base64');
}

/**
 * Hash a password using Node.js native crypto.scrypt (libuv thread pool).
 * Output format matches Better-Auth: "salt:hash" (both hex encoded).
 */
async function nativeScryptHash(password: string): Promise<string> {
  const salt = crypto.randomBytes(16).toString('hex');
  const normalized = password.normalize('NFKC');
  const key = await new Promise<Buffer>((resolve, reject) => {
    crypto.scrypt(normalized, salt, SCRYPT_KEY_LENGTH, SCRYPT_PARAMS, (err, derivedKey) => {
      if (err) reject(err);
      else resolve(derivedKey);
    });
  });
  return `${salt}:${key.toString('hex')}`;
}

/**
 * Verify a password against a Better-Auth scrypt hash using Node.js native crypto.scrypt.
 */
async function nativeScryptVerify(data: { hash: string; password: string }): Promise<boolean> {
  const [salt, storedKey] = data.hash.split(':');
  if (!salt || !storedKey) return false;
  const normalized = data.password.normalize('NFKC');
  const key = await new Promise<Buffer>((resolve, reject) => {
    crypto.scrypt(normalized, salt, SCRYPT_KEY_LENGTH, SCRYPT_PARAMS, (err, derivedKey) => {
      if (err) reject(err);
      else resolve(derivedKey);
    });
  });
  return crypto.timingSafeEqual(key, Buffer.from(storedKey, 'hex'));
}

/**
 * Cached auto-generated secret for the current server instance.
 * Generated once at a module load to ensure consistency within a single run.
 */
let cachedAutoGeneratedSecret: null | string = null;

/**
 * Cached project app name for the current server instance.
 * Read once from package.json to avoid repeated file reads.
 */
let cachedProjectAppName: null | string = null;

export interface CreateBetterAuthOptions {
  /**
   * Better-auth configuration from server options
   */
  config: IBetterAuth;

  /**
   * MongoDB database instance
   * Note: Uses 'any' type to handle version incompatibilities between
   * mongoose's bundled mongodb types and the project's mongodb package.
   * At runtime, this is a mongodb.Db instance.
   */
  db: any;

  /**
   * Fallback secrets to try if no betterAuth.secret is configured.
   * The array is iterated and the first valid secret (≥32 chars) is used.
   * If no valid secret is found, an auto-generated secret is used.
   *
   * Typical usage: Pass existing secrets from your config (e.g., jwt.secret)
   * for backwards compatibility.
   *
   * @example
   * ```typescript
   * fallbackSecrets: [config.jwt?.secret, config.jwt?.refresh?.secret]
   * ```
   */
  fallbackSecrets?: (string | undefined)[];

  /**
   * Callback for when email is verified (to sync verifiedAt)
   * Injected from CoreBetterAuthModule
   */
  onEmailVerified?: OnEmailVerifiedCallback;

  /**
   * Callback for sending verification email
   * Injected from CoreBetterAuthModule to use NestJS services
   */
  sendVerificationEmail?: SendVerificationEmailCallback;

  /**
   * Server-level app/frontend URL (from IServerOptions.appUrl).
   * Used for Passkey origin and CORS trustedOrigins.
   */
  serverAppUrl?: string;

  /**
   * Server-level base URL (from IServerOptions.baseUrl).
   * Used as fallback for betterAuth.baseUrl.
   */
  serverBaseUrl?: string;

  /**
   * Server-level CORS configuration (from IServerOptions.cors).
   * Used to align BetterAuth's trustedOrigins with the server-level CORS config.
   *
   * @since 11.25.0
   */
  serverCorsConfig?: boolean | ICorsConfig;

  /**
   * Server environment (from IServerOptions.env).
   * Used for local environment defaults.
   */
  serverEnv?: string;
}

/**
 * Callback for when email is verified
 * Injected from CoreBetterAuthModule to sync verifiedAt
 */
export type OnEmailVerifiedCallback = (userId: string) => Promise<void>;

/**
 * Options for creating a better-auth instance
 */
/**
 * Callback for sending verification email
 * Injected from CoreBetterAuthModule to use NestJS services
 */
export type SendVerificationEmailCallback = (options: {
  token: string;
  url: string;
  user: { email: string; id: string; name?: null | string };
}) => Promise<void>;

/**
 * Invoke an auth-email send (verification / password-reset) fire-and-forget.
 *
 * Better-Auth recommends NOT awaiting these sends so the response time does not
 * leak whether an account exists (timing attack). The catch here is essential:
 * a rejected send (e.g. SMTP not configured / delivery failure) must never
 * become an unhandled promise rejection — that crashes the Node process (an
 * unverified sign-up + sign-in took the whole API down in dev). This wrapper
 * keeps the send non-blocking while routing every failure (sync throw or async
 * rejection) to `onError` instead. `onError` itself is guarded too: if the
 * handler throws, the error is swallowed rather than crashing the process.
 *
 * Deliberate divergence from Better-Auth's own mechanism: Better-Auth awaits
 * these callbacks via `runInBackgroundOrAwait` and offers
 * `advanced.backgroundTasks` as its native non-blocking path. That option is
 * global (it detaches ALL background tasks — OTP, invites, password reset, …)
 * and routes failures to Better-Auth's internal logger instead of the NestJS
 * logger, so this wrapper detaches only the sends the framework owns. Projects
 * can still opt into `advanced.backgroundTasks` via the `options` passthrough.
 */
export function sendAuthEmailSafely(send: () => unknown, onError: (error: unknown) => void): void {
  void Promise.resolve()
    .then(send)
    .catch((error) => {
      try {
        onError(error);
      } catch {
        // Last resort: the error handler itself failed. Swallowing here keeps
        // the no-unhandled-rejection guarantee — a throwing handler must not
        // crash the process this helper exists to protect.
      }
    });
}

/**
 * Better-Auth field type definition
 * Matches the DBFieldType from better-auth
 */
type BetterAuthFieldType = 'boolean' | 'date' | 'json' | 'number' | 'number[]' | 'string' | 'string[]';

/**
 * Normalized Passkey configuration with required fields
 */
interface NormalizedPasskeyConfig {
  authenticatorAttachment?: 'cross-platform' | 'platform';
  challengeStorage?: 'cookie' | 'database';
  challengeTtlSeconds?: number;
  origin: string;
  residentKey?: 'discouraged' | 'preferred' | 'required';
  rpId: string;
  rpName: string;
  userVerification?: 'discouraged' | 'preferred' | 'required';
  webAuthnChallengeCookie?: string;
}

/**
 * Result of Passkey configuration normalization
 */
interface PasskeyNormalizationResult {
  /**
   * Whether Passkey should be enabled after normalization
   */
  enabled: boolean;

  /**
   * Normalized Passkey configuration (with auto-detected values)
   */
  normalizedConfig: NormalizedPasskeyConfig | null;

  /**
   * Auto-detected trustedOrigins (to be merged with config)
   */
  trustedOrigins: null | string[];

  /**
   * Warnings generated during normalization
   */
  warnings: string[];
}

/**
 * Social provider configuration for better-auth
 */
interface SocialProviderConfig {
  clientId: string;
  clientSecret: string;
}

/**
 * User field configuration type for Better-Auth
 * Matches the DBFieldAttribute structure from better-auth
 */
interface UserFieldConfig {
  defaultValue?: unknown;
  fieldName?: string;
  /**
   * Whether a client may supply this field's value via Better-Auth's native input parsing
   * (sign-up create / update-user). When `false`, Better-Auth rejects client-supplied values
   * (throws FIELD_NOT_ALLOWED on update, silently substitutes the server default on create).
   * Defaults to `true` in Better-Auth when omitted. Used to lock server-managed fields
   * (e.g. `roles`) so authenticated users cannot self-set them.
   */
  input?: boolean;
  required?: boolean;
  type: BetterAuthFieldType;
}

/**
 * Validation result for configuration
 */
interface ValidationResult {
  errors: string[];
  resolvedSecret?: string;
  valid: boolean;
  warnings: string[];
}

/**
 * Creates a better-auth instance based on configuration
 *
 * @param options - Configuration options including betterAuth config and MongoDB connection
 * @returns Configured better-auth instance or null if not enabled
 * @throws Error if configuration validation fails
 */
export interface CreateBetterAuthResult {
  /** Resolved cookie domain for cross-subdomain cookies, or undefined if disabled */
  cookieDomain: string | undefined;
  /** The better-auth instance */
  instance: BetterAuthInstance;
}

export function createBetterAuthInstance(options: CreateBetterAuthOptions): CreateBetterAuthResult | null {
  const { config, db, fallbackSecrets, onEmailVerified, sendVerificationEmail, serverEnv } = options;

  // Return null only if better-auth is explicitly disabled
  // BetterAuth is enabled by default (zero-config)
  if (config?.enabled === false) {
    return null;
  }

  // Resolve URLs with auto-detection and local defaults
  const resolvedUrls = resolveUrls(options);

  // Log URL resolution warnings
  for (const warning of resolvedUrls.warnings) {
    logger.log(warning);
  }

  // Normalize Passkey configuration with auto-detection from resolved URLs
  // This must happen BEFORE validation to allow graceful degradation
  // Passkey is now AUTO-ACTIVATED by default (not opt-in)
  const passkeyNormalization = normalizePasskeyConfig(config, { resolvedUrls, serverEnv });

  // Log passkey normalization warnings (info about auto-detection or disabled status)
  for (const warning of passkeyNormalization.warnings) {
    logger.warn(warning);
  }

  // Validate configuration (with fallback secrets for backwards compatibility)
  const validation = validateConfig(config, { fallbackSecrets, passkeyNormalization });

  // Log warnings
  for (const warning of validation.warnings) {
    logger.warn(warning);
  }

  // Throw on validation errors
  if (!validation.valid) {
    throw new Error(`BetterAuth configuration invalid: ${validation.errors.join('; ')}`);
  }

  // Build configuration components (pass normalized passkey config and resolved URLs)
  const plugins = buildPlugins(config, { passkeyNormalization, serverEnv });
  const socialProviders = buildSocialProviders(config);
  const trustedOrigins = buildTrustedOrigins(config, {
    passkeyNormalization,
    resolvedUrls,
    serverCorsConfig: options.serverCorsConfig,
  });
  const additionalFields = buildUserFields(config);

  // Resolve cross-subdomain cookies (Boolean Shorthand)
  const crossSubDomain = resolveCrossSubDomainCookies(config, resolvedUrls);
  if (crossSubDomain.enabled) {
    logger.log(`Cross-subdomain cookies enabled (domain: ${crossSubDomain.domain})`);
  }

  // Build email verification configuration
  const emailVerificationConfig = buildEmailVerificationConfig(config, { onEmailVerified, sendVerificationEmail });

  // Build the base Better-Auth configuration
  // Use resolved baseUrl (with local defaults) or fallback
  const basePath = config.basePath || '/iam';
  // Cookie prefix for Better-Auth's session cookies (e.g. 'iam.session_token').
  // COOKIE_PREFIX env (always wins) lets a project fully isolate its auth
  // cookies on a shared host; otherwise derived from basePath. The SAME pure
  // resolver is used by every session-cookie call site (service, controller,
  // web/cookie helpers) so the name stays in lockstep.
  const cookiePrefix = resolveBetterAuthCookiePrefix(basePath);
  // Operator visibility: make a non-default COOKIE_PREFIX override obvious in the
  // logs, and remind that the frontend must mirror it or auth will break.
  if ((process.env.COOKIE_PREFIX || '').trim()) {
    logger.log(
      `COOKIE_PREFIX override active → auth cookies use prefix "${cookiePrefix}" ` +
        `(e.g. "${cookiePrefix}.session_token"). The frontend NUXT_PUBLIC_COOKIE_PREFIX MUST match.`,
    );
  }

  // Better-Auth base URL (resolved localhost defaults → explicit config → fallback).
  const betterAuthBaseUrl = resolvedUrls.baseUrl || config.baseUrl || 'http://localhost:3000';
  // The `Secure` attribute Better-Auth WOULD derive for its cookies if `useSecureCookies`
  // were not pinned below: an `https://` baseURL is Better-Auth's own signal
  // (createCookieGetter → `baseURLString.startsWith('https://')`). We keep exactly this value so
  // the pinned `useSecureCookies: false` (needed for name alignment, see below) does not silently
  // strip `Secure` from the cookies Better-Auth's native handlers forward.
  const secureCookies = betterAuthBaseUrl.startsWith('https://');

  const betterAuthConfig: Record<string, unknown> = {
    advanced: {
      cookiePrefix,
      ...(crossSubDomain.enabled && {
        crossSubDomainCookies: { domain: crossSubDomain.domain, enabled: true },
      }),
      // Keep Better-Auth's NATIVE handlers on the SAME cookie name the
      // nest-server cookie helpers actually write. Those helpers always emit
      // the UNPREFIXED `<cookiePrefix>.session_token`. Better-Auth, left to its
      // own devices on an `https://` baseURL, auto-enables secure cookies AND
      // prefixes the name with `__Secure-`, so its native handlers (2FA
      // enable/disable, passkey register/list, backup codes, `/token`) look for
      // `__Secure-<cookiePrefix>.session_token` — a cookie that is never written
      // — and return `401 UNAUTHORIZED`, while the project's own session
      // resolver (which reads the unprefixed cookie) still returns a session: a
      // split-brain where `GET /iam/get-session` is 200 but every sensitive
      // Better-Auth endpoint is 401. Pinning `useSecureCookies: false` keeps the
      // native read path aligned with the cookie helper.
      useSecureCookies: false,
      // …BUT `useSecureCookies: false` also forces `secure: false` on EVERY cookie
      // Better-Auth sets (createCookieGetter → `secure: !!secureCookiePrefix`), and the
      // native handlers forward their `Set-Cookie` VERBATIM via `sendWebResponse`
      // (2FA verify, social callback, magic link, passkey) WITHOUT passing through the
      // cookie helper — so those session cookies would ship without `Secure` in
      // production. Restore the exact Secure flag Better-Auth itself would have derived
      // (an `https://` baseURL), keeping the unprefixed NAME while preserving the
      // `Secure` TRANSPORT flag. Only injected on https so http/local and a consumer's
      // own `options.advanced.useSecureCookies` override are left untouched.
      ...(secureCookies && { defaultCookieAttributes: { secure: true } }),
    },
    basePath,
    baseURL: betterAuthBaseUrl,
    database: mongodbAdapter(db),
    // Enable email/password authentication by default (required by Better-Auth 1.x)
    // Can be disabled by setting config.emailAndPassword.enabled = false
    emailAndPassword: {
      // Defense in Depth: This native Better-Auth flag is the second layer.
      // The first layer is CoreBetterAuthService.ensureSignUpEnabled() which
      // runs in Controller/Resolver BEFORE the BetterAuth API is called and
      // returns a structured LTNS_0026 error. The native flag acts as a safety
      // net in case the custom check is bypassed (e.g., direct API calls).
      disableSignUp: config.emailAndPassword?.disableSignUp === true,
      enabled: config.emailAndPassword?.enabled !== false,
      password: {
        hash: nativeScryptHash,
        verify: nativeScryptVerify,
      },
    },
    plugins,
    secret: validation.resolvedSecret || config.secret,
    socialProviders,
    user: {
      additionalFields,
      modelName: 'users',
    },
  };

  // Add email verification config if enabled
  if (emailVerificationConfig) {
    betterAuthConfig.emailVerification = emailVerificationConfig;
  }

  // Only add trustedOrigins if explicitly configured
  // When undefined, Better-Auth uses its default CORS behavior (allows all origins)
  if (trustedOrigins) {
    betterAuthConfig.trustedOrigins = trustedOrigins;
  }

  // Merge with custom options passthrough
  // This allows projects to configure any Better-Auth option not explicitly defined
  // Deep-merge 'advanced' to preserve cookiePrefix when options.advanced is provided
  let finalConfig: Record<string, unknown>;
  if (config.options) {
    const { advanced: optionsAdvanced, ...restOptions } = config.options as Record<string, unknown>;
    finalConfig = { ...betterAuthConfig, ...restOptions };
    if (optionsAdvanced && typeof optionsAdvanced === 'object') {
      // Drift guard: a programmatic `options.advanced.cookiePrefix` would only
      // change what Better-Auth itself sets — the NestJS layer keeps resolving
      // through `resolveBetterAuthCookiePrefix(basePath, env)`, so sign-in /
      // read / sign-out would silently fall out of lockstep. Loud warning so
      // operators see the misconfiguration immediately. Use `COOKIE_PREFIX`
      // (env) instead — it is honoured by every call site.
      const driftWarning = detectCookiePrefixDrift(cookiePrefix, optionsAdvanced);
      if (driftWarning) logger.warn(driftWarning);
      finalConfig.advanced = {
        ...(betterAuthConfig.advanced as Record<string, unknown>),
        ...(optionsAdvanced as Record<string, unknown>),
        // `defaultCookieAttributes` needs a DEEP merge, not the shallow spread above.
        // It is the key that carries our restored `secure: true` (see the `useSecureCookies: false`
        // block), so a consumer setting it for an entirely unrelated reason — `{ partitioned: true }`,
        // `{ domain: … }` — would wholesale-replace the object and silently strip `Secure` from every
        // session cookie the native handlers forward (2FA verify, social callback, magic link) on an
        // https deployment. Session-establishing cookies, in the clear, with no error anywhere.
        // Re-apply `secure: true` as the BASE and let the consumer's keys spread over it, so an
        // EXPLICIT `secure: false` still wins while an unrelated key can no longer clobber it.
        ...(secureCookies && {
          defaultCookieAttributes: {
            secure: true,
            ...((optionsAdvanced as Record<string, unknown>).defaultCookieAttributes as
              | Record<string, unknown>
              | undefined),
          },
        }),
      };
    }
  } else {
    finalConfig = betterAuthConfig;
  }

  // Create and return the better-auth instance with resolved metadata
  // Type assertion needed for maximum flexibility - allows projects to use any Better-Auth option

  return {
    cookieDomain: crossSubDomain.enabled ? crossSubDomain.domain : undefined,
    instance: betterAuth(finalConfig as any),
  };
}

/**
 * Formats a package name to a human-readable display name.
 * Converts kebab-case and snake_case to Title Case.
 *
 * @example
 * formatProjectName('my-awesome-app')     // → 'My Awesome App'
 * formatProjectName('@org/my-app')        // → 'My App'
 * formatProjectName('nest_server_starter') // → 'Nest Server Starter'
 */
export function formatProjectName(name: string): string {
  // Remove scope (e.g., '@org/my-app' → 'my-app')
  let formatted = name.replace(/^@[^/]+\//, '');

  // Split by hyphens and underscores, capitalize each word
  formatted = formatted
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ');

  return formatted;
}

/**
 * Builds the email verification configuration for Better-Auth.
 *
 * Email verification is enabled by default unless explicitly disabled.
 * Uses the sendVerificationEmail callback to send emails via NestJS services.
 *
 * @param config - Better-auth configuration
 * @param callbacks - Optional callbacks for email verification lifecycle
 * @returns Email verification config for Better-Auth or null if disabled
 */
function buildEmailVerificationConfig(
  config: IBetterAuth,
  callbacks?: {
    onEmailVerified?: OnEmailVerifiedCallback;
    sendVerificationEmail?: SendVerificationEmailCallback;
  },
): null | Record<string, unknown> {
  const { onEmailVerified, sendVerificationEmail } = callbacks ?? {};
  // Email verification is enabled by default (zero-config):
  // - undefined/null: enabled with defaults
  // - true: enabled with defaults
  // - false: explicitly disabled
  // - { ... }: enabled with custom settings (unless enabled: false)
  const emailVerificationConfig = config.emailVerification;

  if (emailVerificationConfig === false) {
    return null;
  }

  if (typeof emailVerificationConfig === 'object' && emailVerificationConfig.enabled === false) {
    return null;
  }

  // Get configuration values (with defaults)
  const configObj = typeof emailVerificationConfig === 'object' ? emailVerificationConfig : {};
  const expiresIn = configObj.expiresIn ?? 86400; // 24 hours
  const autoSignInAfterVerification = configObj.autoSignInAfterVerification ?? true;

  const result: Record<string, unknown> = {
    autoSignInAfterVerification,
    expiresIn,
    // Also send on sign-in if user is not verified
    sendOnSignIn: true,
    // Send verification email on sign-up by default
    sendOnSignUp: true,
  };

  // Add sendVerificationEmail callback if provided
  if (sendVerificationEmail) {
    result.sendVerificationEmail = async (
      data: { token: string; url: string; user: { email: string; id: string; name?: null | string } },
      _request?: Request,
    ) => {
      // Fire-and-forget (timing-attack mitigation, per Better-Auth docs) — but a
      // failed send must be logged, never crash the process (see sendAuthEmailSafely).
      // Note: delivery failures are also logged (with masked recipient) by the
      // email-verification service before rethrowing; this line additionally
      // covers failures thrown outside the service's own try/catch.
      sendAuthEmailSafely(
        () => sendVerificationEmail(data),
        (error) =>
          logger.error(
            `Failed to send verification email: ${error instanceof Error ? error.message : 'Unknown error'}`,
            error instanceof Error ? error.stack : undefined,
          ),
      );
    };
  }

  // Add callback for when email is verified (to sync verifiedAt)
  if (onEmailVerified) {
    result.afterEmailVerification = async (user: string | { id: string }, _request?: Request) => {
      // Better-Auth passes a user object { id: string } to afterEmailVerification
      const userId = typeof user === 'string' ? user : user.id;
      await onEmailVerified(userId);
    };
  }

  return result;
}

/**
 * Builds the plugins array based on configuration.
 * Merges built-in plugins (jwt, twoFactor, passkey) with custom plugins from config.
 *
 * Plugins accept both boolean and object configuration:
 * - `true` or `{}`: Enable with defaults
 * - `{ option: value }`: Enable with custom settings
 * - `false` or `{ enabled: false }`: Disable
 * - `undefined`: Disabled (default)
 *
 * @param config - Better-auth configuration
 * @param options - Additional options
 * @param options.passkeyNormalization - Normalized passkey configuration from normalizePasskeyConfig()
 * @param options.serverEnv - Server environment for auto-detected app name suffix
 */
function buildPlugins(
  config: IBetterAuth,
  options: { passkeyNormalization: PasskeyNormalizationResult; serverEnv?: string },
): BetterAuthPlugin[] {
  const { passkeyNormalization, serverEnv } = options;
  const plugins: BetterAuthPlugin[] = [];

  // JWT Plugin for API client compatibility
  // JWT is enabled by default unless explicitly disabled (jwt: false or jwt: { enabled: false })
  const jwtExplicitlyDisabled =
    config.jwt === false || (typeof config.jwt === 'object' && config.jwt?.enabled === false);
  if (!jwtExplicitlyDisabled) {
    const jwtConfig = typeof config.jwt === 'object' ? config.jwt : {};
    plugins.push(
      jwt({
        jwt: {
          expirationTime: jwtConfig.expiresIn || '15m',
        },
      }),
    );
  }

  // Two-Factor Authentication Plugin
  // 2FA is enabled by default unless explicitly disabled (twoFactor: false or twoFactor: { enabled: false })
  const twoFactorExplicitlyDisabled =
    config.twoFactor === false || (typeof config.twoFactor === 'object' && config.twoFactor?.enabled === false);
  if (!twoFactorExplicitlyDisabled) {
    const twoFactorConfig = typeof config.twoFactor === 'object' ? config.twoFactor : {};
    plugins.push(
      twoFactor({
        // issuer: Use explicit config, or auto-detect from package.json with environment suffix
        issuer: twoFactorConfig.appName || getProjectAppName(serverEnv),
      }),
    );
  }

  // Passkey/WebAuthn Plugin
  // Uses normalized config from normalizePasskeyConfig() which handles auto-detection
  if (passkeyNormalization.enabled && passkeyNormalization.normalizedConfig) {
    const normalizedPasskey = passkeyNormalization.normalizedConfig;

    // Build passkey options from normalized config
    const passkeyOptions: Record<string, unknown> = {
      origin: normalizedPasskey.origin,
      rpID: normalizedPasskey.rpId,
      rpName: normalizedPasskey.rpName,
    };

    // Add optional WebAuthn configuration if specified
    if (normalizedPasskey.authenticatorAttachment) {
      passkeyOptions.authenticatorAttachment = normalizedPasskey.authenticatorAttachment;
    }
    if (normalizedPasskey.residentKey) {
      passkeyOptions.residentKey = normalizedPasskey.residentKey;
    }
    if (normalizedPasskey.userVerification) {
      passkeyOptions.userVerification = normalizedPasskey.userVerification;
    }
    if (normalizedPasskey.webAuthnChallengeCookie) {
      passkeyOptions.webAuthnChallengeCookie = normalizedPasskey.webAuthnChallengeCookie;
    }

    plugins.push(passkey(passkeyOptions));
  }

  // Merge custom plugins from configuration
  // This allows projects to add any Better-Auth plugin without modifying this package
  if (config.plugins?.length) {
    plugins.push(...(config.plugins as BetterAuthPlugin[]));
  }

  return plugins;
}

/**
 * Builds the social providers configuration object dynamically.
 * Iterates over all configured providers and includes those that are enabled
 * with valid clientId and clientSecret.
 */
function buildSocialProviders(config: IBetterAuth): Record<string, SocialProviderConfig> {
  const socialProvidersConfig: Record<string, SocialProviderConfig> = {};

  // Iterate over all configured social providers dynamically
  // A provider is enabled by default if it has credentials configured
  // It can be explicitly disabled by setting enabled: false
  if (config.socialProviders) {
    for (const [name, provider] of Object.entries(config.socialProviders)) {
      if (provider?.clientId && provider?.clientSecret && provider?.enabled !== false) {
        socialProvidersConfig[name] = {
          clientId: provider.clientId,
          clientSecret: provider.clientSecret,
        };
      }
    }
  }

  return socialProvidersConfig;
}

/**
 * Builds the trusted origins array for CORS configuration.
 *
 * Behavior (in priority order):
 * 1. Explicit betterAuth.trustedOrigins → use those (always takes precedence)
 * 2. Server CORS disabled → empty array (adds no extra trusted origins beyond BetterAuth's own
 *    baseURL — see NOTE; it does NOT switch BetterAuth's origin check off)
 * 3. Server CORS allowAll → fall through to rules 4-7 (see below)
 * 4. Server CORS allowedOrigins → merge with appUrl/baseUrl
 * 5. Passkey trustedOrigins → use from normalizePasskeyConfig()
 * 6. Fallback to resolved appUrl
 * 7. Otherwise → undefined (Better-Auth then trusts only its own baseURL)
 *
 * NOTE on rules 2 and 7: neither an empty array (rule 2) nor `undefined` (rule 7) means "any
 * origin is allowed", and neither disables BetterAuth's origin check. In both cases BetterAuth
 * still derives and trusts its own `baseURL` origin (see `getTrustedOrigins()` in
 * `better-auth/context`, which unconditionally pushes `new URL(baseURL).origin` before appending
 * `options.trustedOrigins`), so `[]` and `undefined` are behaviorally identical here: a
 * separately hosted frontend is still rejected by every origin-checked endpoint.
 *
 * @param config - Better-auth configuration
 * @param options - Passkey normalization, resolved URLs, and server CORS context
 */
export function buildTrustedOrigins(
  config: IBetterAuth,
  options: {
    passkeyNormalization: PasskeyNormalizationResult;
    resolvedUrls: ResolvedUrls;
    serverCorsConfig?: boolean | ICorsConfig;
  },
): string[] | undefined {
  const { passkeyNormalization, resolvedUrls, serverCorsConfig } = options;

  // 1. Explicit betterAuth.trustedOrigins always takes precedence (backward compatible)
  if (config.trustedOrigins?.length) {
    return config.trustedOrigins;
  }

  // 2. Server CORS disabled → add no extra trusted origins. BetterAuth still trusts its own
  //    baseURL (see the NOTE above), so this does NOT turn its origin check off — it only means
  //    "no separately hosted frontend is trusted". Behaviorally identical to rule 7's undefined.
  if (serverCorsConfig === false || (typeof serverCorsConfig === 'object' && serverCorsConfig?.enabled === false)) {
    return [];
  }

  // 3. Server CORS allowAll → fall through to the appUrl / passkey rules below.
  //
  // This used to `return undefined` in the belief that BetterAuth then "allows all
  // origins". It does not: without trustedOrigins BetterAuth trusts only its own
  // baseURL, so the *app* origin is rejected and every origin-checked endpoint
  // (two-factor/enable, passkey) answers 403 INVALID_ORIGIN. That silently broke
  // 2FA and passkeys in exactly the setups that use allowAll — local dev and CI.
  //
  // An origin check has no meaningful "allow everything" mode — that is the very
  // thing it defends against — so allowAll now yields the known-good origins
  // (appUrl, passkey) instead of none. Projects that really do want to accept
  // arbitrary origins can still set `betterAuth.trustedOrigins` explicitly (rule 1).

  // 4. Server allowedOrigins → merge with appUrl/baseUrl.
  // Order (appUrl, baseUrl, allowedOrigins) mirrors buildCorsConfig() in cookies.helper.ts
  // for consistency — the final Set is order-equivalent, but the array order helps readers
  // trace which value came from which source.
  if (typeof serverCorsConfig === 'object' && serverCorsConfig?.allowedOrigins?.length) {
    const origins: string[] = [];
    if (resolvedUrls.appUrl) origins.push(resolvedUrls.appUrl);
    if (resolvedUrls.baseUrl) origins.push(resolvedUrls.baseUrl);
    origins.push(...serverCorsConfig.allowedOrigins);
    return [...new Set(origins)];
  }

  // 5. If Passkey is enabled, use the trustedOrigins from normalization
  if (passkeyNormalization.enabled && passkeyNormalization.trustedOrigins?.length) {
    return passkeyNormalization.trustedOrigins;
  }

  // 6. Fallback to resolved appUrl (for CORS even without Passkey)
  if (resolvedUrls.appUrl) {
    return [resolvedUrls.appUrl];
  }

  // 7. Otherwise, let Better-Auth handle CORS with its default behavior
  return undefined;
}

/**
 * Server-managed, security-critical user fields whose `input: false` MUST be re-asserted after
 * merging project-supplied `additionalUserFields`, so a project override cannot silently re-open
 * a protected key. Each of these, if client-settable, is a concrete vulnerability:
 *
 * - `roles`            → vertical privilege escalation (self-granting `admin`)
 * - `verified`         → email-verification bypass
 * - `verifiedAt`       → email-verification bypass
 * - `twoFactorEnabled` → self-toggling the 2FA state
 * - `iamId`            → identity / account-linking hijack
 *
 * Note: `termsAndPrivacyAcceptedAt` is server-managed by default (input:false above) but is
 * intentionally NOT hard-locked here — a project may legitimately choose to accept a client-set
 * consent timestamp; it is not a privilege boundary.
 *
 * These protections only concern Better-Auth's native input parsing (sign-up / update-user).
 * nest-server's own role assignment (UserService/CrudService `checkRoles` + Mongoose writes,
 * `setRoles`, and the user mapper's native `$set` writes) does NOT use Better-Auth input parsing
 * and is therefore unaffected by `input: false`.
 */
const PROTECTED_INPUT_FALSE_KEYS = ['iamId', 'roles', 'twoFactorEnabled', 'verified', 'verifiedAt'] as const;

/**
 * Builds the user additional fields configuration.
 * Merges core fields (firstName, lastName, etc.) with custom fields from config.
 * Custom fields override core fields if they have the same key.
 */
function buildUserFields(config: IBetterAuth): Record<string, UserFieldConfig> {
  // Core fields required for nest-server functionality
  const coreFields: Record<string, UserFieldConfig> = {
    firstName: {
      defaultValue: null,
      fieldName: 'firstName',
      type: 'string',
    },
    iamId: {
      defaultValue: null,
      fieldName: 'iamId',
      // Server-managed: linked to the Better-Auth identity by the user mapper (native DB write),
      // never from client input. input:false blocks identity/account-linking hijack.
      input: false,
      type: 'string',
    },
    lastName: {
      defaultValue: null,
      fieldName: 'lastName',
      type: 'string',
    },
    roles: {
      defaultValue: [],
      fieldName: 'roles',
      // Server-managed: assigned via UserService/CrudService (checkRoles guard) + setRoles,
      // never from client input. input:false blocks vertical privilege escalation
      // (e.g. a self-registered user POSTing {"roles":["admin"]} to /iam/update-user).
      input: false,
      type: 'string[]',
    },
    // Track when terms and privacy policy were accepted (for sign-up checks)
    termsAndPrivacyAcceptedAt: {
      defaultValue: null,
      fieldName: 'termsAndPrivacyAcceptedAt',
      // Server-managed consent timestamp: set by the sign-up flow, not client input.
      input: false,
      type: 'date',
    },
    twoFactorEnabled: {
      defaultValue: false,
      fieldName: 'twoFactorEnabled',
      // Server-managed: toggled by the 2FA enable/disable flow, never from client input.
      // input:false blocks self-toggling the 2FA state.
      input: false,
      type: 'boolean',
    },
    verified: {
      defaultValue: false,
      fieldName: 'verified',
      // Server-managed: synced from Better-Auth email verification, never from client input.
      // input:false blocks email-verification bypass.
      input: false,
      type: 'boolean',
    },
    // Track when email was verified (synced from Better-Auth)
    verifiedAt: {
      defaultValue: null,
      fieldName: 'verifiedAt',
      // Server-managed: synced from Better-Auth email verification, never from client input.
      // input:false blocks email-verification bypass.
      input: false,
      type: 'date',
    },
  };

  // Merge with custom additional fields from configuration
  // Custom fields can override core fields or add new ones.
  // The `input` flag is carried through so projects can mark their own fields as server-managed.
  if (config.additionalUserFields) {
    for (const [key, field] of Object.entries(config.additionalUserFields)) {
      coreFields[key] = {
        defaultValue: field.defaultValue,
        fieldName: field.fieldName || key,
        input: field.input,
        required: field.required,
        type: field.type,
      };
    }
  }

  // Security: re-assert input:false on server-managed, security-critical fields AFTER the merge,
  // so a project-supplied additionalUserFields override cannot silently re-open a protected key
  // (privilege escalation, email-verification bypass, 2FA bypass, identity hijack).
  for (const key of PROTECTED_INPUT_FALSE_KEYS) {
    if (coreFields[key]) {
      coreFields[key].input = false;
    }
  }

  // Security (defense-in-depth): the loop above keys on the well-known object key. A project could
  // still reopen a protected COLUMN by registering a shadow field under a different key that maps to
  // it, e.g. `additionalUserFields: { customRoles: { fieldName: 'roles', input: true } }`. Lock any
  // such field too, so no additionalUserFields entry — regardless of its key — can feed client input
  // into a protected column.
  const protectedColumns = new Set<string>(PROTECTED_INPUT_FALSE_KEYS);
  for (const [key, field] of Object.entries(coreFields)) {
    if (!protectedColumns.has(key) && field.fieldName && protectedColumns.has(field.fieldName)) {
      field.input = false;
    }
  }

  return coreFields;
}

/**
 * Formats the environment name as a suffix.
 * Only adds suffix for development/test environments.
 *
 * @example
 * formatEnvSuffix('local')      // → '(Local)'
 * formatEnvSuffix('development') // → '(Development)'
 * formatEnvSuffix('test')       // → '(Test)'
 * formatEnvSuffix('production') // → '' (no suffix for production)
 * formatEnvSuffix(undefined)    // → ''
 */
function formatEnvSuffix(env?: string): string {
  if (!env) return '';

  // Don't add suffix for production
  if (env === 'production' || env === 'prod') return '';

  // Capitalize first letter
  const formatted = env.charAt(0).toUpperCase() + env.slice(1).toLowerCase();
  return `(${formatted})`;
}

/**
 * Gets or generates the fallback secret for development.
 * The secret is cached to ensure consistency during the server's lifetime.
 */
function getAutoGeneratedSecret(): string {
  if (!cachedAutoGeneratedSecret) {
    cachedAutoGeneratedSecret = generateSecureSecret();
  }
  return cachedAutoGeneratedSecret;
}

/**
 * Gets the project's app name from package.json.
 *
 * This function reads the `name` field from the project's package.json
 * and formats it for display (converts a kebab-case to Title Case).
 *
 * Used as default for:
 * - `betterAuth.passkey.rpName` (displayed in browser Passkey prompts)
 * - `betterAuth.twoFactor.appName` (displayed in authenticator apps)
 *
 * @param serverEnv - Optional server environment to append as suffix (e.g., 'local' → '(Local)')
 * @returns The formatted project name, or 'Nest Server' as fallback
 *
 * @example
 * // package.json: { "name": "my-awesome-app" }
 * getProjectAppName()           // → 'My Awesome App'
 * getProjectAppName('local')    // → 'My Awesome App (Local)'
 * getProjectAppName('test')     // → 'My Awesome App (Test)'
 */
function getProjectAppName(serverEnv?: string): string {
  // Return cached value if available (without env suffix, will be added after)
  if (cachedProjectAppName === null) {
    cachedProjectAppName = readProjectNameFromPackageJson();
  }

  // Add environment suffix for non-production environments
  // This helps developers distinguish Passkeys when running multiple projects locally
  const envSuffix = formatEnvSuffix(serverEnv);
  return envSuffix ? `${cachedProjectAppName} ${envSuffix}` : cachedProjectAppName;
}

/**
 * Checks if a secret has valid minimum length (32 characters)
 */
function isValidSecretLength(secret: string): boolean {
  return secret && secret.length >= 32;
}

/**
 * Validates a URL string
 */
function isValidUrl(url: string): boolean {
  try {
    new URL(url);
    return true;
  } catch {
    return false;
  }
}

/**
 * Reads the project name from package.json in the current working directory.
 * Falls back to 'Nest Server' if package.json cannot be read or has no name.
 */
function readProjectNameFromPackageJson(): string {
  const fallback = 'Nest Server';

  try {
    const packageJsonPath = path.join(process.cwd(), 'package.json');
    const packageJsonContent = fs.readFileSync(packageJsonPath, 'utf-8');
    const packageJson = JSON.parse(packageJsonContent);

    if (packageJson.name && typeof packageJson.name === 'string') {
      return formatProjectName(packageJson.name);
    }
  } catch {
    // Ignore errors - use fallback
  }

  return fallback;
}

/**
 * Resolves the effective URLs for BetterAuth configuration.
 *
 * Resolution priority:
 * 1. Explicit betterAuth config values
 * 2. Server-level URLs (IServerOptions.baseUrl, IServerOptions.appUrl)
 * 3. Auto-derived values (appUrl from baseUrl)
 * 4. Local environment defaults (when env: 'local')
 *
 * @param options - CreateBetterAuthOptions containing config and server URLs
 * @returns Resolved URLs with warnings for logging
 */
interface ResolvedUrls {
  appUrl: string | undefined;
  baseUrl: string | undefined;
  rpId: string | undefined;
  warnings: string[];
}

/**
 * Extracts the root domain from a URL for use as Passkey rpId.
 *
 * For localhost: Returns 'localhost' (not 'localhost:3000')
 * For domains: Returns the registrable domain (e.g., 'example.com')
 *
 * Examples:
 * - 'https://api.example.com' → 'example.com'
 * - 'https://app.dev.example.com' → 'example.com'
 * - 'http://localhost:3000' → 'localhost'
 * - 'https://example.com' → 'example.com'
 *
 * @param url - The URL to extract rpId from
 * @returns The root domain suitable for Passkey rpId
 */
function extractRpIdFromUrl(url: string): string {
  try {
    const parsedUrl = new URL(url);
    const hostname = parsedUrl.hostname;

    // localhost is a special case
    if (hostname === 'localhost' || hostname === '127.0.0.1') {
      return 'localhost';
    }

    // For regular domains, extract the registrable domain
    // This is a simplified approach - for complex TLDs like .co.uk, a library would be better
    const parts = hostname.split('.');

    // If it's just a simple domain (example.com), return it
    if (parts.length <= 2) {
      return hostname;
    }

    // For subdomains, return the last two parts (example.com from api.example.com)
    // Note: This doesn't handle .co.uk style TLDs correctly, but works for common cases
    return parts.slice(-2).join('.');
  } catch {
    return 'localhost';
  }
}

/**
 * Normalizes Passkey configuration with auto-detection from resolved URLs.
 *
 * **AUTO-ACTIVATION:** Passkey is enabled by default when BetterAuth is active.
 * It is only disabled when:
 * 1. Explicitly disabled: `passkey: false` or `passkey: { enabled: false }`
 * 2. Required URLs cannot be resolved (Graceful Degradation)
 *
 * Auto-Detection Logic (using resolvedUrls from resolveUrls()):
 * - `rpId`: from passkey.rpId > resolvedUrls.rpId (derived from appUrl)
 * - `origin`: from passkey.origin > resolvedUrls.appUrl
 * - `trustedOrigins`: from config.trustedOrigins > [resolvedUrls.appUrl]
 *
 * @param config - Better-auth configuration
 * @param options - Additional options
 * @param options.resolvedUrls - Resolved URLs from resolveUrls()
 * @param options.serverEnv - Server environment for auto-detected app name suffix
 * @returns Normalization result with enabled status, config, and warnings
 */
function normalizePasskeyConfig(
  config: IBetterAuth,
  options: { resolvedUrls: ResolvedUrls; serverEnv?: string },
): PasskeyNormalizationResult {
  const { resolvedUrls, serverEnv } = options;
  const warnings: string[] = [];

  // Check if Passkey is explicitly DISABLED
  // passkey: false OR passkey: { enabled: false }
  const isExplicitlyDisabled =
    config.passkey === false || (typeof config.passkey === 'object' && config.passkey?.enabled === false);

  if (isExplicitlyDisabled) {
    return { enabled: false, normalizedConfig: null, trustedOrigins: null, warnings };
  }

  // Get the raw passkey config (if object)
  const rawConfig = typeof config.passkey === 'object' ? config.passkey : {};

  // Resolve values: explicit config > resolved URLs
  const finalRpId = rawConfig.rpId || resolvedUrls.rpId;
  const finalOrigin = rawConfig.origin || resolvedUrls.appUrl;
  const finalTrustedOrigins = config.trustedOrigins?.length
    ? config.trustedOrigins
    : resolvedUrls.appUrl
      ? [resolvedUrls.appUrl]
      : undefined;

  // Check if we have all required values for Passkey
  const hasRequiredConfig = finalRpId && finalOrigin && finalTrustedOrigins?.length;

  if (!hasRequiredConfig) {
    // Graceful Degradation: Disable Passkey with warning
    const missingFields: string[] = [];
    if (!finalRpId) missingFields.push('rpId');
    if (!finalOrigin) missingFields.push('origin');
    if (!finalTrustedOrigins?.length) missingFields.push('trustedOrigins');

    warnings.push(
      `⚠️ PASSKEY DISABLED: Cannot auto-detect required values (${missingFields.join(', ')}). ` +
        'To enable Passkey, set baseUrl in your config or configure passkey values explicitly.',
    );
    warnings.push(
      'Fix options:\n' +
        '  1. Set baseUrl: "https://api.example.com" → auto-detects appUrl, rpId, origin\n' +
        '  2. Set env: "local" → uses localhost:3000 (API) and localhost:3001 (App) defaults\n' +
        '  3. Disable Passkey explicitly: passkey: false (no warning)',
    );

    return { enabled: false, normalizedConfig: null, trustedOrigins: null, warnings };
  }

  // Log auto-detection info
  if (!rawConfig.rpId && resolvedUrls.rpId) {
    warnings.push(`PASSKEY: Using rpId="${finalRpId}" (auto-detected from appUrl)`);
  }
  if (!rawConfig.origin && resolvedUrls.appUrl) {
    warnings.push(`PASSKEY: Using origin="${finalOrigin}" (= appUrl)`);
  }
  if (!config.trustedOrigins?.length && resolvedUrls.appUrl) {
    warnings.push(`PASSKEY: Using trustedOrigins=${JSON.stringify(finalTrustedOrigins)} (= [appUrl])`);
  }

  // Build normalized config
  // rpName: Use explicit config, or auto-detect from package.json with environment suffix
  const normalizedConfig: NormalizedPasskeyConfig = {
    origin: finalOrigin,
    rpId: finalRpId,
    rpName: rawConfig.rpName || getProjectAppName(serverEnv),
  };

  // Copy optional fields from explicit config
  if (rawConfig.authenticatorAttachment) {
    normalizedConfig.authenticatorAttachment = rawConfig.authenticatorAttachment;
  }
  if (rawConfig.challengeStorage) {
    normalizedConfig.challengeStorage = rawConfig.challengeStorage;
  }
  if (rawConfig.challengeTtlSeconds) {
    normalizedConfig.challengeTtlSeconds = rawConfig.challengeTtlSeconds;
  }
  if (rawConfig.residentKey) {
    normalizedConfig.residentKey = rawConfig.residentKey;
  }
  if (rawConfig.userVerification) {
    normalizedConfig.userVerification = rawConfig.userVerification;
  }
  if (rawConfig.webAuthnChallengeCookie) {
    normalizedConfig.webAuthnChallengeCookie = rawConfig.webAuthnChallengeCookie;
  }

  return {
    enabled: true,
    normalizedConfig,
    trustedOrigins: finalTrustedOrigins,
    warnings,
  };
}

/**
 * Result of cross-subdomain cookies resolution
 */
export interface ResolvedCrossSubDomainCookies {
  /** The resolved cookie domain (e.g., 'example.com') */
  domain: string | undefined;
  /** Whether cross-subdomain cookies are enabled */
  enabled: boolean;
}

/**
 * Re-exported for backward compatibility.
 *
 * @deprecated Import from `./better-auth-cookie-prefix.helper` directly. The
 * re-export exists only so callers that landed on `./better-auth.config`
 * before the helper was extracted keep working; new code MUST import from the
 * dedicated helper module to avoid pulling the heavy config-builder into the
 * dependency graph (which forces import cycles in some build setups).
 */
export { resolveBetterAuthCookiePrefix, resolveBetterAuthSessionCookieName } from './better-auth-cookie-prefix.helper';

/**
 * Resolves the cross-subdomain cookies configuration.
 *
 * Follows the Boolean Shorthand Pattern:
 * - `undefined` / `false` → disabled
 * - `true` / `{}` → enabled, domain auto-derived from appUrl or baseUrl
 * - `{ domain: 'x.com' }` → enabled with explicit domain
 * - `{ enabled: false }` → disabled (allows pre-configuration)
 *
 * Domain auto-derivation priority:
 * 1. Explicit `crossSubDomainCookies.domain`
 * 2. `appUrl` hostname (e.g., `https://dev.example.com` → `dev.example.com`)
 * 3. `baseUrl` hostname with `api.` prefix stripped (e.g., `https://api.dev.example.com` → `dev.example.com`)
 * 4. `baseUrl` hostname as-is (if no `api.` prefix)
 *
 * The parent domain is preferred because cross-subdomain cookies need to cover
 * both the API subdomain and the App domain (e.g., `api.dev.example.com` ↔ `dev.example.com`).
 *
 * @param config - Better-auth configuration
 * @param resolvedUrls - Resolved URLs for domain auto-detection
 * @returns Resolved cross-subdomain cookie settings
 */
export function resolveCrossSubDomainCookies(
  config: IBetterAuth,
  resolvedUrls: ResolvedUrls,
): ResolvedCrossSubDomainCookies {
  const csdc = config.crossSubDomainCookies;

  // undefined or false → disabled
  if (csdc === undefined || csdc === null || csdc === false) {
    return { domain: undefined, enabled: false };
  }

  // Object with enabled: false → disabled (pre-configuration)
  if (typeof csdc === 'object' && csdc.enabled === false) {
    return { domain: undefined, enabled: false };
  }

  // true or {} or { domain: ... } → enabled
  const explicitDomain = typeof csdc === 'object' ? csdc.domain : undefined;

  if (explicitDomain) {
    return { domain: explicitDomain, enabled: true };
  }

  // Auto-derive domain: prefer appUrl (= parent domain), then strip api. from baseUrl
  const domain = deriveCookieDomainFromUrls(resolvedUrls.appUrl, resolvedUrls.baseUrl || config.baseUrl);
  if (domain) {
    return { domain, enabled: true };
  }

  // No usable URL available → cannot derive domain, disable
  return { domain: undefined, enabled: false };
}

/**
 * Derives the cookie domain from available URLs.
 *
 * For cross-subdomain cookies, the domain must be the PARENT domain that covers
 * both the API and App subdomains. For example:
 * - API: `api.dev.example.com`, App: `dev.example.com` → domain: `dev.example.com`
 *
 * Resolution:
 * 1. Use appUrl hostname (if available and not localhost)
 * 2. Strip `api.` prefix from baseUrl hostname
 * 3. Use baseUrl hostname as-is
 *
 * Returns undefined for localhost (cross-subdomain not meaningful there).
 *
 * The `api.` strip reuses {@link strippedApiHostname} so it shares that helper's guard against
 * bogus results: `api.dev` → `dev` would set a public-suffix cookie domain that browsers reject
 * outright (dropping every session cookie), so `api.dev` is kept as-is instead.
 *
 * KNOWN LIMITATION (fails closed, no leak): the single-label guard cannot recognise a MULTI-label
 * public suffix — `api.co.uk` still strips to `co.uk`, a Public-Suffix-List entry browsers also
 * reject, so cross-subdomain auth would break (cookie dropped) rather than over-scope. A full PSL
 * check would need a dependency, which this security-critical module deliberately avoids; for such
 * apex domains set `betterAuth.crossSubDomainCookies.domain` explicitly instead of relying on
 * derivation. See migration guide 11.27.5 → 11.27.6.
 */
function deriveCookieDomainFromUrls(appUrl?: string, baseUrl?: string): string | undefined {
  // Priority 1: appUrl hostname (this IS the parent domain in typical setups)
  if (appUrl) {
    try {
      const hostname = new URL(appUrl).hostname;
      if (hostname !== 'localhost' && hostname !== '127.0.0.1') {
        return hostname;
      }
    } catch {
      // Fall through to baseUrl
    }
  }

  // Priority 2: baseUrl hostname with api. prefix stripped
  if (baseUrl) {
    try {
      const hostname = new URL(baseUrl).hostname;
      if (hostname === 'localhost' || hostname === '127.0.0.1') {
        return undefined;
      }
      // Strip api. prefix to get parent domain — but keep the host unchanged when stripping
      // would leave a bare TLD (`api.dev`) or empty host (`api.`).
      return strippedApiHostname(hostname) ?? hostname;
    } catch {
      return undefined;
    }
  }

  return undefined;
}

function resolveUrls(options: CreateBetterAuthOptions): ResolvedUrls {
  const { config, serverAppUrl, serverBaseUrl, serverCorsConfig, serverEnv } = options;
  const warnings: string[] = [];

  // Steps 1+2 (baseUrl, appUrl) are delegated to the shared resolver in cookies.helper so that
  // BetterAuth's trustedOrigins and the REST/GraphQL CORS allowlist can never disagree about
  // which app origin this server is reachable under. `cors.deriveAppUrl: false` therefore
  // suppresses the `api.`-strip derivation on this layer too.
  const corsObj = typeof serverCorsConfig === 'object' && serverCorsConfig !== null ? serverCorsConfig : undefined;
  const resolved = resolveServerUrls({
    appUrl: serverAppUrl,
    // Priority: betterAuth.baseUrl > serverBaseUrl (> localhost default, applied by the resolver)
    baseUrl: config.baseUrl || serverBaseUrl,
    deriveAppUrl: corsObj?.deriveAppUrl,
    env: serverEnv,
  });
  const { appUrl, baseUrl } = resolved;

  if (resolved.baseUrlSource === 'localhost-default') {
    warnings.push(`URL: Using localhost default baseUrl="${baseUrl}" (env: '${serverEnv}')`);
  }
  if (resolved.appUrlSource === 'localhost-default') {
    warnings.push(`URL: Using localhost default appUrl="${appUrl}" (env: '${serverEnv}')`);
  }
  if (resolved.appUrlSource === 'derived' && appUrl !== baseUrl) {
    warnings.push(`URL: Auto-derived appUrl="${appUrl}" from baseUrl="${baseUrl}"`);
  }

  // Step 3: Resolve rpId from appUrl (not baseUrl!)
  // rpId should be the domain where the user authenticates (app domain)
  let rpId: string | undefined;
  if (appUrl) {
    rpId = extractRpIdFromUrl(appUrl);
  }

  return { appUrl, baseUrl, rpId, warnings };
}

/**
 * Validates the better-auth configuration and applies fallback secret if needed.
 * Mutates config.secret if fallback is applied.
 *
 * Secret resolution order:
 * 1. betterAuth.secret (if configured and valid)
 * 2. First valid secret from fallbackSecrets array (≥32 chars)
 * 3. Auto-generated secure secret (with warning)
 *
 * @param config - Better-auth configuration
 * @param options - Optional validation context (fallback secrets, passkey normalization)
 */
function validateConfig(
  config: IBetterAuth,
  options?: {
    fallbackSecrets?: (string | undefined)[];
    passkeyNormalization?: PasskeyNormalizationResult;
  },
): ValidationResult {
  const { fallbackSecrets, passkeyNormalization } = options ?? {};
  const errors: string[] = [];
  const warnings: string[] = [];

  // Track secret source for appropriate messaging
  let secretSource: 'auto-generated' | 'explicit' | 'fallback' = 'explicit';
  let resolvedSecret = config.secret;

  // Resolve secret with fallback chain (without mutating the config object)
  if (!resolvedSecret || resolvedSecret.trim() === '') {
    // Try fallback secrets in order
    const validFallback = fallbackSecrets?.find((secret) => secret && isValidSecretLength(secret));

    if (validFallback) {
      resolvedSecret = validFallback;
      secretSource = 'fallback';
    } else {
      // Last resort: auto-generate
      resolvedSecret = getAutoGeneratedSecret();
      secretSource = 'auto-generated';
    }
  }

  // Validate the resolved secret
  const secretValidation = validateSecret(resolvedSecret);
  if (!secretValidation.valid) {
    errors.push(secretValidation.message!);
  } else if (secretValidation.message) {
    warnings.push(secretValidation.message);
  }

  // Log information about secret source
  switch (secretSource) {
    case 'auto-generated':
      warnings.push('BETTER_AUTH: No secret configured - using auto-generated secret.');
      warnings.push('CONSEQUENCE: All user sessions will be invalidated on server restart!');
      warnings.push(
        'FOR PRODUCTION: Set betterAuth.secret in config or provide a valid fallback secret (min 32 chars).',
      );
      warnings.push("Generate with: node -e \"console.log(require('crypto').randomBytes(32).toString('base64'))\"");
      break;
    case 'fallback':
      warnings.push(
        'BETTER_AUTH: Using fallback secret (backwards compatible). Consider setting betterAuth.secret explicitly.',
      );
      break;
    // 'explicit' - no warning needed, explicitly configured
  }

  // Validate baseUrl
  if (config.baseUrl && !isValidUrl(config.baseUrl)) {
    errors.push(`Invalid baseUrl format: ${config.baseUrl}`);
  }

  // Validate trustedOrigins (if explicitly configured)
  if (config.trustedOrigins) {
    for (const origin of config.trustedOrigins) {
      if (!isValidUrl(origin)) {
        errors.push(`Invalid trustedOrigin format: ${origin}`);
      }
    }
  }

  // Validate auto-detected trustedOrigins from passkey normalization
  if (passkeyNormalization?.trustedOrigins) {
    for (const origin of passkeyNormalization.trustedOrigins) {
      if (!isValidUrl(origin)) {
        errors.push(`Invalid auto-detected trustedOrigin format: ${origin}`);
      }
    }
  }

  // Validate passkey origin (only if passkey is enabled after normalization)
  if (passkeyNormalization?.enabled && passkeyNormalization.normalizedConfig) {
    const normalizedOrigin = passkeyNormalization.normalizedConfig.origin;
    if (!isValidUrl(normalizedOrigin)) {
      errors.push(`Invalid passkey origin format: ${normalizedOrigin}`);
    }
  }

  // Validate social providers dynamically
  // Providers are enabled by default unless explicitly disabled (enabled: false)
  // We only validate credentials for providers that are not explicitly disabled
  if (config.socialProviders) {
    for (const [name, provider] of Object.entries(config.socialProviders)) {
      // Provider is considered active if: configured AND not explicitly disabled
      if (provider && provider.enabled !== false) {
        // Validate that credentials are provided for active providers
        const hasClientId = !!provider.clientId;
        const hasClientSecret = !!provider.clientSecret;

        if (hasClientId && hasClientSecret) {
          // Both credentials present - provider is fully configured
          continue;
        } else if (hasClientId || hasClientSecret) {
          // Only one credential provided - this is an error
          if (!hasClientId) {
            errors.push(`Social provider '${name}' is missing clientId`);
          }
          if (!hasClientSecret) {
            errors.push(`Social provider '${name}' is missing clientSecret`);
          }
        } else {
          // No credentials provided, but the provider is configured and not disabled
          // This is likely a configuration mistake - warn the user
          warnings.push(
            `Social provider '${name}' is configured but missing both clientId and clientSecret. ` +
              `Set 'enabled: false' to disable it explicitly, or provide credentials to enable it.`,
          );
        }
      }
    }
  }

  return {
    errors,
    resolvedSecret,
    valid: errors.length === 0,
    warnings,
  };
}

/**
 * Validates the secret strength
 * Requirements: min 32 chars, should contain mixed characters
 */
function validateSecret(secret: string): { message?: string; valid: boolean } {
  if (!secret || secret.length < 32) {
    return { message: 'Secret must be at least 32 characters long', valid: false };
  }

  // Check for character diversity (at least 2 of: lowercase, uppercase, numbers, special)
  const hasLowercase = /[a-z]/.test(secret);
  const hasUppercase = /[A-Z]/.test(secret);
  const hasNumbers = /[0-9]/.test(secret);
  const hasSpecial = /[^a-zA-Z0-9]/.test(secret);
  const diversityCount = [hasLowercase, hasUppercase, hasNumbers, hasSpecial].filter(Boolean).length;

  if (diversityCount < 2) {
    return {
      message: 'Secret should contain at least 2 different character types (lowercase, uppercase, numbers, special)',
      valid: true, // Warning only, not an error
    };
  }

  return { valid: true };
}
