/**
 * Unit Tests: package.json scripts must run on Windows too.
 *
 * npm and pnpm execute scripts through the platform's shell — `/bin/sh` on POSIX, **cmd.exe** on
 * Windows. cmd.exe has no `VAR=value command` prefix, no `/dev/null`, no `true`, and it passes
 * single quotes through literally instead of grouping an argument. A script using any of those
 * fails on Windows with a message that names the variable, not the script:
 *
 *   > NODE_ENV=local nodemon
 *   Der Befehl "NODE_ENV" ist entweder falsch geschrieben oder konnte nicht gefunden werden.
 *
 * Measured on a Windows laptop on 2026-09-16 against a project generated by `lt fullstack init`:
 * `pnpm run start:local` never reached nodemon. The fix is `cross-env`, and this suite is what
 * keeps the prefix from coming back — the same guard the lt CLI carries as
 * `__tests__/package-scripts-portable.test.ts`.
 *
 * Chained commands are the trap worth knowing: in `a && VAR=x b`, a leading `cross-env` binds to
 * `a` only, so every link needs its own. The env-prefix pattern below is therefore NOT anchored to
 * the start of the string.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

const ROOT = join(__dirname, '..', '..');
const scripts: Record<string, string> = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')).scripts ?? {};
const entries = Object.entries(scripts);

/** `VAR=value` at the start of a command — also after `&&`, `||`, `;` or `|`. */
const ENV_PREFIX = /(^|[\s;&|(])[A-Z_][A-Z0-9_]*=\S/;

/**
 * Programs a script may not call, by name. Adopted verbatim from nest-server-starter's
 * `package-scripts-portable.spec.ts` (PR #54, extended in #55). Two kinds, deliberately in one list:
 *   - absent under cmd.exe: `bash`, `cp`, `rm`, `touch`, …
 *   - PRESENT under cmd.exe, but a different program with the same name: `mkdir` (no `-p`; the `/` in
 *     `dist/types` is read as a switch), `find` (a text search), `sort`, `timeout` (waits, runs
 *     nothing), `rmdir`. A name-only rule catches these too, and more honestly than a "command plus
 *     forbidden switch" rule would: the switch set is open-ended, and none of them is needed in a
 *     script — `cpy` creates target directories, `rimraf` removes them, Node does the rest.
 * `echo` is not listed: unquoted it behaves the same, and quoted it is caught by the quote rule.
 */
const POSIX_ONLY = [
  '[',
  'awk',
  'bash',
  'cat',
  'chmod',
  'cp',
  'cut',
  'export',
  'find',
  'grep',
  'head',
  'kill',
  'ln',
  'ls',
  'lsof',
  'mkdir',
  'mv',
  'open',
  'pgrep',
  'pkill',
  'printf',
  'rm',
  'rmdir',
  'sed',
  'sh',
  'sleep',
  'sort',
  'source',
  'tail',
  'test',
  'timeout',
  'touch',
  'tr',
  'true',
  'wc',
  'which',
  'xargs',
  'xdg-open',
];

/**
 * POSIX shell syntax that no program name reveals: a function definition (`f() { …; }; f`) and the
 * positional parameters it takes (`"$1"`, `$@`). cmd.exe understands neither.
 */
const SHELL_SYNTAX = /\b[\w-]+\s*\(\)\s*\{|\$[0-9@*#]/;

/** The program in command position of every link in a `&&` / `||` / `;` / `|` chain. */
function commandNames(command: string): string[] {
  return command
    .split(/&&|\|\||;|\|/)
    .map((link) =>
      link
        .trim()
        .replace(/^cross-env\s+/, '')
        .replace(/^(?:[A-Z_][A-Z0-9_]*=\S+\s+)+/, ''),
    )
    .map((link) => link.split(/\s+/)[0])
    .filter(Boolean);
}

const offenders = (re: RegExp) => entries.filter(([, command]) => re.test(command)).map(([name]) => name);

describe('package.json scripts are portable', () => {
  it('has scripts at all (guards against a silently empty suite)', () => {
    expect(entries.length).toBeGreaterThan(10);
  });

  it('sets environment variables through cross-env, never a POSIX prefix', () => {
    // cross-env's own argument is the legal form and must not be reported: strip it first.
    const withoutCrossEnv = entries.map(
      ([name, command]) => [name, command.replace(/cross-env\s+(?:[A-Z_][A-Z0-9_]*=\S+\s+)+/g, '')] as const,
    );
    const bad = withoutCrossEnv.filter(([, command]) => ENV_PREFIX.test(command)).map(([name]) => name);
    expect(bad, `cmd.exe has no "VAR=value command" — prefix these with cross-env: ${bad.join(', ')}`).toEqual([]);
  });

  it('does not redirect to /dev/null', () => {
    const bad = offenders(/\/dev\/null/);
    expect(bad, `/dev/null does not exist on Windows: ${bad.join(', ')}`).toEqual([]);
  });

  it('does not swallow failures with `|| true`', () => {
    const bad = offenders(/\|\|\s*true\b/);
    expect(bad, `cmd.exe has no "true" builtin: ${bad.join(', ')}`).toEqual([]);
  });

  it('quotes arguments with double quotes, not single ones', () => {
    // `test:cleanup` is the one exception, and it is listed rather than silently skipped: it shells
    // out to POSIX `find`, which Windows does not have at all (`find.exe` there is a text search).
    // Quoting alone would not make it run, so it needs a rewrite in Node — separate work, tracked
    // by this list. A SECOND offender fails the suite, which is the point of naming the first.
    const KNOWN_UNPORTABLE = ['test:cleanup'];
    const bad = offenders(/'/).filter((name) => !KNOWN_UNPORTABLE.includes(name));
    expect(bad, `cmd.exe passes single quotes through literally: ${bad.join(', ')}`).toEqual([]);
    expect(
      KNOWN_UNPORTABLE.filter((name) => scripts[name] !== undefined && /'/.test(scripts[name])),
      'a script left this list — drop it from KNOWN_UNPORTABLE',
    ).toEqual(KNOWN_UNPORTABLE.filter((name) => scripts[name] !== undefined));
  });

  it('declares cross-env as an exact devDependency', () => {
    const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
    const version = pkg.devDependencies?.['cross-env'];
    const usesCrossEnv = entries.some(([, command]) => /(^|\s)cross-env\s/.test(command));
    if (!usesCrossEnv) return; // nothing needs it — do not force the dependency
    expect(version, 'scripts call cross-env, so it must be declared').toBeDefined();
    expect(version, 'fixed versions only — no ^ or ~').toMatch(/^\d+\.\d+\.\d+$/);
  });
});

/** The programs of `command` that cmd.exe lacks or runs as something else. */
function unportablePrograms(command: string): string[] {
  return commandNames(command).filter((program) => POSIX_ONLY.includes(program));
}

/**
 * Asserts the offenders of one rule: nothing outside `known`, and every entry of `known` still
 * offending — a list that does not shrink with the fixes stops meaning anything.
 */
function expectOnlyKnown(found: string[], known: string[], rule: string): void {
  const bad = found.filter((name) => !known.includes(name));
  expect(bad, `${rule}: ${bad.join(', ')}`).toEqual([]);
  expect([...found].sort(), `a script left the known list of "${rule}" — drop it from the list`).toEqual(
    known.filter((name) => scripts[name] !== undefined).sort(),
  );
}

describe('commandNames — the detector itself', () => {
  it('reads the program of every link in a chain', () => {
    expect(commandNames('pnpm run docs:ci && open http://x/ && compodoc -s')).toEqual(['pnpm', 'open', 'compodoc']);
    expect(commandNames('cpy ./bin ./dist/ || exit 0')).toEqual(['cpy', 'exit']);
    expect(commandNames('a; b | c')).toEqual(['a', 'b', 'c']);
  });

  it('looks past cross-env and its assignments', () => {
    expect(commandNames('cross-env NODE_ENV=e2e A=1 find tests -delete')).toEqual(['find']);
  });

  it('does not mistake an argument for a program', () => {
    expect(commandNames('node scripts/open.mjs ./find ./bash')).toEqual(['node']);
  });
});

describe('unportablePrograms / SHELL_SYNTAX — the rules themselves', () => {
  // Samples from this repository's unfixed build scripts, where the mkdir gap was found.
  it('flags mkdir -p on its own, not only because cp follows it', () => {
    expect(unportablePrograms('mkdir -p dist/types && cp src/types/*.d.ts dist/types/')).toEqual(['mkdir', 'cp']);
    expect(unportablePrograms('mkdir -p dist/types && cpy "src/types/*.d.ts" dist/types/')).toEqual(['mkdir']);
  });

  it('flags cmd.exe builtins that share a name but not a meaning', () => {
    expect(unportablePrograms('sort -u list.txt')).toEqual(['sort']);
    expect(unportablePrograms('timeout 5 node x.js')).toEqual(['timeout']);
  });

  it('accepts the portable replacements', () => {
    expect(unportablePrograms('rimraf dist && tsc -p tsconfig.build.json && cpy ./a ./dist/ || exit 0')).toEqual([]);
    expect(unportablePrograms('node scripts/copy-build-assets.mjs types')).toEqual([]);
  });

  it('sees a shell function and its positional parameters', () => {
    expect(SHELL_SYNTAX.test('f() { migrate create "$1"; }; f')).toBe(true);
    // Each half on its own, so neither can be dropped behind the other's back.
    expect(SHELL_SYNTAX.test('clean() { rimraf dist; }; clean')).toBe(true);
    expect(SHELL_SYNTAX.test('node x.js "$@"')).toBe(true);
    expect(SHELL_SYNTAX.test('migrate create --template-file ./t.ts')).toBe(false);
    expect(SHELL_SYNTAX.test('cpy ./package.json --rename=meta.json ./dist/')).toBe(false);
  });
});

describe('package.json scripts call no program cmd.exe lacks', () => {
  it('does not call a program that cmd.exe lacks or runs as something else', () => {
    // Listed rather than silently skipped. `bash scripts/check-server-start.sh` gets a Node
    // replacement shared across the repos that carry it; `docs` (`open`) and `test:cleanup` (POSIX
    // `find`) are developer conveniences outside the build and the test run.
    expectOnlyKnown(
      entries.filter(([, command]) => unportablePrograms(command).length > 0).map(([name]) => name),
      ['check:fix', 'check:naf', 'check:raw', 'docs', 'test:cleanup'],
      'not available under cmd.exe',
    );
  });

  it('does not use POSIX shell functions or positional parameters', () => {
    // No known exceptions here: this repository has no `migrate:create` (the starter's is one).
    expectOnlyKnown(
      entries.filter(([, command]) => SHELL_SYNTAX.test(command)).map(([name]) => name),
      [],
      'POSIX shell syntax',
    );
  });
});
