/**
 * Unit Tests: package.json scripts must run on Windows too.
 *
 * npm and pnpm execute scripts through the platform's shell — `/bin/sh` on POSIX, **cmd.exe** on
 * Windows. cmd.exe has no `VAR=value command` prefix, no `/dev/null`, no `true`, and it passes
 * single quotes through literally instead of grouping an argument. A script using any of those
 * fails on Windows with a message that names the variable, not the script:
 *
 *   > NODE_ENV=local nodemon
 *   Der Befehl "NODE_ENV" ist entweder falsch geschrieben oder konnte nicht gefunden werden.
 *
 * Measured on a Windows laptop on 2026-09-16 against a project generated by `lt fullstack init`:
 * `pnpm run start:local` never reached nodemon. The fix is `cross-env`, and this suite is what
 * keeps the prefix from coming back — the same guard the lt CLI carries as
 * `__tests__/package-scripts-portable.test.ts`.
 *
 * Chained commands are the trap worth knowing: in `a && VAR=x b`, a leading `cross-env` binds to
 * `a` only, so every link needs its own. The env-prefix pattern below is therefore NOT anchored to
 * the start of the string.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

const ROOT = join(__dirname, '..', '..');
const scripts: Record<string, string> = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')).scripts ?? {};
const entries = Object.entries(scripts);

/** `VAR=value` at the start of a command — also after `&&`, `||`, `;` or `|`. */
const ENV_PREFIX = /(^|[\s;&|(])[A-Z_][A-Z0-9_]*=\S/;

const offenders = (re: RegExp) => entries.filter(([, command]) => re.test(command)).map(([name]) => name);

describe('package.json scripts are portable', () => {
  it('has scripts at all (guards against a silently empty suite)', () => {
    expect(entries.length).toBeGreaterThan(10);
  });

  it('sets environment variables through cross-env, never a POSIX prefix', () => {
    // cross-env's own argument is the legal form and must not be reported: strip it first.
    const withoutCrossEnv = entries.map(
      ([name, command]) => [name, command.replace(/cross-env\s+(?:[A-Z_][A-Z0-9_]*=\S+\s+)+/g, '')] as const,
    );
    const bad = withoutCrossEnv.filter(([, command]) => ENV_PREFIX.test(command)).map(([name]) => name);
    expect(bad, `cmd.exe has no "VAR=value command" — prefix these with cross-env: ${bad.join(', ')}`).toEqual([]);
  });

  it('does not redirect to /dev/null', () => {
    const bad = offenders(/\/dev\/null/);
    expect(bad, `/dev/null does not exist on Windows: ${bad.join(', ')}`).toEqual([]);
  });

  it('does not swallow failures with `|| true`', () => {
    const bad = offenders(/\|\|\s*true\b/);
    expect(bad, `cmd.exe has no "true" builtin: ${bad.join(', ')}`).toEqual([]);
  });

  it('quotes arguments with double quotes, not single ones', () => {
    // `test:cleanup` is the one exception, and it is listed rather than silently skipped: it shells
    // out to POSIX `find`, which Windows does not have at all (`find.exe` there is a text search).
    // Quoting alone would not make it run, so it needs a rewrite in Node — separate work, tracked
    // by this list. A SECOND offender fails the suite, which is the point of naming the first.
    const KNOWN_UNPORTABLE = ['test:cleanup'];
    const bad = offenders(/'/).filter((name) => !KNOWN_UNPORTABLE.includes(name));
    expect(bad, `cmd.exe passes single quotes through literally: ${bad.join(', ')}`).toEqual([]);
    expect(
      KNOWN_UNPORTABLE.filter((name) => scripts[name] !== undefined && /'/.test(scripts[name])),
      'a script left this list — drop it from KNOWN_UNPORTABLE',
    ).toEqual(KNOWN_UNPORTABLE.filter((name) => scripts[name] !== undefined));
  });

  it('declares cross-env as an exact devDependency', () => {
    const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
    const version = pkg.devDependencies?.['cross-env'];
    const usesCrossEnv = entries.some(([, command]) => /(^|\s)cross-env\s/.test(command));
    if (!usesCrossEnv) return; // nothing needs it — do not force the dependency
    expect(version, 'scripts call cross-env, so it must be declared').toBeDefined();
    expect(version, 'fixed versions only — no ^ or ~').toMatch(/^\d+\.\d+\.\d+$/);
  });
});
