name: Publish

on:
  release:
    types:
      - released

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13]
        mongodb-version: [4.4]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.13
        uses: actions/setup-node@v1
        with:
          node-version: 16.13

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4

      - name: Install dependencies
        run: npm install

      - name: Optimize and check
        run: npm run prepublishOnly

      - name: Build
        run: npm run build

      - uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}
